const paragraph = document.querySelector('#p-1');
const a1 = document.querySelector('.a1');
const a2 = document.querySelector('.a2');
const a3 = document.querySelector('.a3');
console.log(a1);
console.log(a2);
console.log(a3);
console.log(paragraph);
paragraph.innerHTML = '.این یک پاراگراف است';
a1.title = 'دیجیکالا';
a2.title = 'آپارات';
a3.title = 'کنکوریوم';