const link1 = document.querySelector('.link-1');
const link2 = document.querySelector('.link-2');
const link3 = document.querySelector('.link-3');
const link4 = document.querySelector('.link-4');
const link5 = document.querySelector('.link-5');
const link6 = document.querySelector('.link-6');
const link7 = document.querySelector('.link-7');
const p1 = document.querySelector('.paragraph');
console.log(link1);
console.log(link2);
console.log(link3);
console.log(link4);
console.log(link5);
console.log(link6);
console.log(link7);
console.log(p1);
p1.innerHTML = '| Hello World Wide Web |';
link1.title = 'Google';
link2.title = 'Youtube';
link3.title = 'Whatsapp';
link4.title = 'Twitter';
link5.title = 'Snapchat';
link6.title = 'Telegram';
link7.title = 'Pintrest';