const title1 = document.querySelector('.nav-link1');
const title2 = document.querySelector('.nav-link2');
const title3 = document.querySelector('.nav-link3');
const title4 = document.querySelector('.nav-link4');
const title7 = document.querySelector('.fav-icon');
title1.setAttribute('title', 'Contact Us');
title2.setAttribute('title', 'About Us');
title3.setAttribute('title', 'Questions');
title4.setAttribute('title', 'Services');
title7.setAttribute('title', 'fav-icon');
let a = 20;
let more = a + 10;
